# Generated by Django 4.2.30 on 2026-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_bulk_create_users_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="oidc_sub",
            field=models.CharField(
                blank=True,
                help_text="The `sub` claim from the OIDC provider, if this user was created or linked via OIDC login.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
